name = "consia-avatar-os"
main = "worker.js"
compatibility_date = "2026-01-01"

[[r2_buckets]]
binding = "AVATAR_BUCKET"
bucket_name = "consia-avatars"

[[d1_databases]]
binding = "DB"
database_name = "consia_d1"
database_id = "1b1010cf-2247-4ba3-903a-4da26323bab3"
